export const typeScriptPlanningPhases = Object.freeze([
  "program-index",
  "generated-names",
  "pointer-flow",
  "scalar-flow",
  "effect-candidates",
  "effect-calls",
  "effect-projections",
  "effect-invocation-inputs",
  "effect-projection-candidate-calls",
  "effect-projection-candidate-accesses",
  "effect-projection-candidate-bindings",
  "effect-projection-candidate-order",
  "effect-value-slot-bindings",
  "effect-value-slot-binding-projections",
  "effect-value-slot-structural-escapes",
  "effect-value-slot-structural-mutations",
  "effect-value-slot-batch",
  "effect-value-slot-roots",
  "effect-value-slot-graph",
  "effect-value-slot-components",
  "effect-value-slot-resolution",
  "effect-callable-projections",
  "effect-indirect-results",
  "effect-indirect-value-collections",
  "effect-indirect-storage-fields",
  "effect-indirect-storage-declarations",
  "effect-indirect-storage-parameters",
  "effect-indirect-storage-references",
  "effect-indirect-storage-carriers",
  "effect-indirect-storage-topology",
  "effect-indirect-storage-ingress",
  "effect-indirect-storage-invocations",
  "effect-indirect-storage-value-flows",
  "effect-indirect-storage-boundaries",
  "effect-indirect-value-storage",
  "effect-indirect-value-finalization",
  "effect-indirect-value-inputs",
  "effect-indirect-graph",
  "effect-indirect-resolution",
  "effect-indirect-origin-index",
  "effect-indirect-round",
  "effect-indirect-invocations",
  "effect-interface-contracts",
  "effect-interface-calls",
  "effect-interface-call-analysis",
  "effect-interface-call-inputs",
  "effect-interface-call-processing",
  "effect-interface-call-transports",
  "effect-interface-context-transports",
  "effect-interface-implementation-inputs",
  "effect-interface-value-slots",
  "effect-interface-origins",
  "effect-interface-components",
  "effect-interface-dispatch",
  "effect-callable-transport-inputs",
  "effect-callable-object-projections",
  "effect-callable-calls",
  "effect-callable-bodies",
  "effect-callable-contracts",
  "effect-callable-graph",
  "effect-callable-resolution",
  "effect-callable-origin-index",
  "effect-callable-unsafe-uses",
  "effect-callable-call-resolutions",
  "effect-callable-interface-evidence",
  "effect-callable-query-resolutions",
  "effect-callable-finalization",
  "effect-callable-flow",
  "effect-return-projections",
  "effect-return-locals",
  "effect-return-storage-owners",
  "effect-return-storage-bindings",
  "effect-return-storage-references",
  "effect-return-storage-boundaries",
  "effect-return-inputs",
  "effect-return-inventory",
  "effect-return-graph",
  "effect-return-resolution",
  "effect-return-origin-index",
  "effect-return-finalization",
  "effect-return-flow",
  "effect-result-consumption",
  "effect-classification",
  "effect-propagation",
  "effect-file-plans",
  "effect-summary",
  "representation-flow",
  "source-plans",
] as const);

export type TypeScriptPlanningPhase = typeof typeScriptPlanningPhases[number];

export const typeScriptPlanningMeasurementNames = Object.freeze([
  "batches",
  "boundaries",
  "calls",
  "candidates",
  "closed",
  "components",
  "containsExpansions",
  "containsQueries",
  "contractExpansions",
  "contractQueries",
  "contracts",
  "declarations",
  "edges",
  "frontier",
  "origins",
  "opaqueExpansions",
  "opaqueQueries",
  "planExpansions",
  "planQueries",
  "references",
  "roots",
  "steps",
  "values",
  "valueExpansions",
  "valueQueries",
  "vertices",
] as const);

export type TypeScriptPlanningMeasurementName =
  typeof typeScriptPlanningMeasurementNames[number];

export type TypeScriptPlanningMeasurements = Readonly<
  Partial<Record<TypeScriptPlanningMeasurementName, number>>
>;

export type TypeScriptPlanningObserver = (
  phase: TypeScriptPlanningPhase,
  measurements?: TypeScriptPlanningMeasurements,
) => void;
