export const typeScriptPlanningPhases = Object.freeze([
  "program-index",
  "generated-names",
  "pointer-flow",
  "scalar-flow",
  "effect-candidates",
  "effect-calls",
  "effect-projections",
  "effect-invocation-inputs",
  "effect-projection-candidate-calls",
  "effect-projection-candidate-accesses",
  "effect-projection-candidate-bindings",
  "effect-projection-candidate-order",
  "effect-value-slot-bindings",
  "effect-value-slot-binding-projections",
  "effect-value-slot-roots",
  "effect-value-slot-graph",
  "effect-value-slot-components",
  "effect-value-slot-resolution",
  "effect-callable-projections",
  "effect-indirect-results",
  "effect-indirect-value-collections",
  "effect-indirect-value-constructors",
  "effect-indirect-value-class-references",
  "effect-indirect-storage-fields",
  "effect-indirect-storage-declarations",
  "effect-indirect-storage-parameters",
  "effect-indirect-storage-references",
  "effect-indirect-storage-carriers",
  "effect-indirect-storage-topology",
  "effect-indirect-storage-ingress",
  "effect-indirect-storage-invocations",
  "effect-indirect-storage-value-flows",
  "effect-indirect-storage-boundaries",
  "effect-indirect-value-storage",
  "effect-indirect-value-property-references",
  "effect-indirect-value-inputs",
  "effect-indirect-graph",
  "effect-indirect-resolution",
  "effect-indirect-round",
  "effect-indirect-invocations",
  "effect-interface-dispatch",
  "effect-callable-transport-inputs",
  "effect-callable-object-projections",
  "effect-callable-calls",
  "effect-callable-bodies",
  "effect-callable-contracts",
  "effect-callable-graph",
  "effect-callable-resolution",
  "effect-callable-origin-index",
  "effect-callable-unsafe-uses",
  "effect-callable-call-resolutions",
  "effect-callable-finalization",
  "effect-callable-flow",
  "effect-return-flow",
  "effect-result-consumption",
  "effect-classification",
  "effect-propagation",
  "effect-file-plans",
  "effect-summary",
  "representation-flow",
  "source-plans",
] as const);

export type TypeScriptPlanningPhase = typeof typeScriptPlanningPhases[number];

export type TypeScriptPlanningObserver = (
  phase: TypeScriptPlanningPhase,
) => void;
